<WelcomeScreen>:
    name: "welcomescreen"
    FloatLayout:
        size_hint: (1, 1)
        pos_hint: {"x": 0, "y": 0}
        Image:
            source: "assets/bg.gif"
            allow_stretch: True
            keep_ratio: False
            size_hint: (1, 1)
            pos_hint: {"x": 0, "y": 0}
            anim_delay: 0.1
    BoxLayout:
        orientation: "vertical"
        spacing: 20
        padding: 50
        Image:
            source: "assets/logo2.png"
            size_hint: (1, 0.7)
            allow_stretch: True
            keep_ratio: True
        Button:
            text: "Start"
            font_name:"Bitcount"
            font_size: 30
            size_hint: (0.5, 0.2)
            pos_hint: {"center_x": 0.5}
            on_release:
                app.root.current = "mainmenuscreen" 

<ImageChoosingScreen>:
    name: "melodyscreen"
    FloatLayout:
        size_hint: (1, 1)
        pos_hint: {"x": 0, "y": 0}
        Image:
            source: "assets/bg.gif"
            allow_stretch: True
            keep_ratio: False
            size_hint: (1, 1)
            pos_hint: {"x": 0, "y": 0}
            anim_delay: 0.1
    BoxLayout:
        orientation: "vertical"
        Image:
            id: img
            size_hint_y: 0.7
            allow_stretch: True
            keep_ratio: True
            color: 1, 1, 1, 0
        BoxLayout:
            size_hint_y: 0.15
            Button:
                text: "Import image"
                font_name:"Bitcount"
                font_size: 30
                on_release: root.open_filechooser()
            Button:
                id: start_button
                text: "Start"
                font_name:"Bitcount"
                font_size: 30
                on_release: 
                    app.root.current = "melodysettings"
                    app.root.get_screen("melodysettings").selected_file = root.selected_file                 
        Label:
            id: status
            size_hint_y: 0.1
            text: " "
            font_name:"Bitcount"
            font_size: 20
            canvas.before:
                Color:
                    rgba: 0, 0, 0, 0.7
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [10]

<MainMenuScreen>:
    name:"mainmenuscreen"
    FloatLayout:
        size_hint: (1, 1)
        pos_hint: {"x": 0, "y": 0}
        Image:
            source: "assets/bg.gif"
            allow_stretch: True
            keep_ratio: False
            size_hint: (1, 1)
            pos_hint: {"x": 0, "y": 0}
            anim_delay: 0.1
    BoxLayout:
        orientation: "vertical"
        spacing: 25                   
        size_hint: (0.5, None)       
        height: self.minimum_height   
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        Button:
            text: "Melody"
            font_name:"Bitcount"
            font_size: 30
            size_hint_y: None
            height: 120
            on_release: 
                app.root.current = "melodyscreen"
        Button:
            text: "Game"
            font_name:"Bitcount"
            font_size: 30
            size_hint_y: None
            height: 120
            on_release: 
                app.root.current = "melodyscreen"

<MelodySettingsScreen>:
    name: "melodysettings"
    FloatLayout:
        size_hint: (1, 1)
        pos_hint: {"x": 0, "y": 0}
        Image:
            source: "assets/bg.gif"
            allow_stretch: True
            keep_ratio: False
            size_hint: (1, 1)
            pos_hint: {"x": 0, "y": 0}
            anim_delay: 0.1
    
    BoxLayout:
        orientation: "vertical"
        spacing: 20
        padding: 50

        Label:
            text: "Melody settings"
            font_name:"Bitcount"
            font_size: 40
            size_hint_y: None
            height: 40
            halign: "center"
            valign: "middle"

        BoxLayout:
            orientation: "vertical"
            spacing: 10
            Label:
                text: "Melody instrument:"
                font_name:"Bitcount"
                font_size: 30
                size_hint_y: None
                height: 25
            Spinner:
                id: melody_instrument_spinner
                text: "Piano"
                font_name:"Bitcount"
                font_size: 25
                values: ["Piano", "Organ", "Violin", "Flute", "Accordion", "Guitar", "Bagpipes"]
                size_hint_y: None
                height: 60
                on_text: root.set_melody_instrument(self.text)

        BoxLayout:
            orientation: "vertical"
            spacing: 10
            Label:
                text: "Bass instrument:"
                font_name:"Bitcount"
                font_size: 30
                size_hint_y: None
                height: 25
                
            Spinner:
                id: bass_instrument_spinner
                text: "Piano"
                font_name:"Bitcount"
                font_size: 25
                values: ["Piano", "Organ", "Violin", "Flute", "Accordion", "Guitar", "Bagpipes"]
                size_hint_y: None
                height: 60
                on_text: root.set_bass_instrument(self.text)

        Label:
            text: "Choose the number of octaves"
            font_name:"Bitcount"
            font_size: 30
            size_hint_y: None
            height: 30
            halign: "center"
            valign: "middle"

        BoxLayout:
            id: octave_selector
            orientation: "horizontal"
            size_hint_y: None
            height: 50
            spacing: 10

            ToggleButton:
                text: "2"
                font_name:"Bitcount"
                font_size: 25
                group: "octaves"
                on_state: root.set_octaves([4,5]) if self.state=="down" else None

            ToggleButton:
                text: "3"
                font_name:"Bitcount"
                font_size: 25
                group: "octaves"
                state: "down"  
                on_state: root.set_octaves([3,4,5]) if self.state=="down" else None

            ToggleButton:
                text: "4"
                font_name:"Bitcount"
                font_size: 25
                group: "octaves"
                on_state: root.set_octaves([3,4,5,6]) if self.state=="down" else None

            ToggleButton:
                text: "5"
                font_name:"Bitcount"
                font_size: 25
                group: "octaves"
                on_state: root.set_octaves([3,4,5,6,7]) if self.state=="down" else None

        BoxLayout:
            orientation: "horizontal"
            size_hint_y: None
            height: 40
            spacing: 10
            canvas.before:
                Color:
                    rgba: 0, 0, 0, 0.7
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [10]
            Label:
                text: "Include sharps (#)?"
                font_name:"Bitcount"
                font_size: 30
            CheckBox:
                on_active: root.toggle_sharps(self, self.active)


        Widget:
            size_hint_y: 1

        Button:
            text: "Continue"
            font_name:"Bitcount"
            font_size: 30
            size_hint_y: None
            height: 60
            on_release: root.start_processing()

<LoadingScreen>:
    name: "loadingscreen"
    FloatLayout:
        size_hint: (1, 1)
        pos_hint: {"x": 0, "y": 0}
        Image:
            source: "assets/bg.gif"
            allow_stretch: True
            keep_ratio: False
            size_hint: (1, 1)
            pos_hint: {"x": 0, "y": 0}
            anim_delay: 0.1
    BoxLayout:
        orientation: "vertical"
        spacing: 20
        padding: 50
        Label:
            text: "Melody is generating, please wait..."
            font_name:"Bitcount"
            font_size: 30
        ProgressBar:
            id: progress
            max: 100
            value: 0  

<ResultScreen>:
    name: "resultscreen"
    FloatLayout:
        size_hint: (1, 1)
        pos_hint: {"x": 0, "y": 0}
        Image:
            source: "assets/bg.gif"
            allow_stretch: True
            keep_ratio: False
            size_hint: (1, 1)
            pos_hint: {"x": 0, "y": 0}
            anim_delay: 0.1
    BoxLayout:
        orientation: "vertical"
        spacing: 20
        padding: 50
        Label:
            id: status
            text: "Melody is ready"
            font_name:"Bitcount"
            font_size: 40
        BoxLayout:
            size_hint_y: 0.2
            spacing: 20
            Button:
                text: "Save"
                font_name:"Bitcount"
                font_size: 30
                on_release: root.save_melody()
            Button:
                text: "Play"
                font_name:"Bitcount"
                font_size: 30
                on_release: root.start_processing()
        Button:
            text: "Back to Main Menu"
            font_name:"Bitcount"
            font_size: 30
            size_hint_y: 0.2
            on_release: app.root.current = "mainmenuscreen"
            
<PlayingScreen>:
    name: "playingscreen"
    FloatLayout:
        size_hint: (1, 1)
        pos_hint: {"x": 0, "y": 0}
        Image:
            source: "assets/bg.gif"
            allow_stretch: True
            keep_ratio: False
            size_hint: (1, 1)
            pos_hint: {"x": 0, "y": 0}
            anim_delay: 0.1
    BoxLayout:
        orientation: "vertical"
        padding: 30
        spacing: 20
        FloatLayout:
            Image:
                id: vinyl
                source: "assets/vinyl2.png"
                size_hint: (0.7, 0.7)
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                canvas.before:
                    PushMatrix
                    Rotate:
                        id: rot
                        angle: root.rotation_angle
                        origin: self.center

                canvas.after:
                    PopMatrix

        Label:
            id: time_label
            text: " "
            font_name:"Bitcount"
            font_size: 30
            size_hint_y: None
            height: 40

        ProgressBar:
            id: progress
            max: 100
            value: 0
            size_hint_y: None
            height: 20

        BoxLayout:
            size_hint_y: None
            height: 60
            spacing: 20

            Button:
                id: play_btn
                text: "Play"
                font_name:"Bitcount"
                font_size: 30
                on_release: root.toggle_play_pause()

            Button:
                text: "Return"
                font_name:"Bitcount"
                font_size: 30
                on_release: root.stop_playing()

ScreenManager:
    WelcomeScreen:
    MainMenuScreen:
    ImageChoosingScreen:
    LoadingScreen:
    ResultScreen:
    PlayingScreen:
    MelodySettingsScreen: